# Generated by Django 3.2.21 on 2023-12-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picked_capsule',
            fields=[
                ('account_info_email', models.CharField(max_length=100)),
                ('picked_capsule_id', models.AutoField(primary_key=True, serialize=False)),
                ('info_write_date', models.DateField()),
                ('info_open_date', models.DateField()),
                ('info_content', models.TextField()),
                ('info_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
