# Generated by Django 5.0 on 2023-12-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='image',
            field=models.ImageField(default='media/default_image.jpeg', upload_to=''),
        ),
    ]
