# Generated by Django 5.0 on 2023-12-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_picked_capsule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
