# Generated by Django 3.2.21 on 2023-12-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_id'),
        ('main', '0004_alter_capsule_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
    ]
