# Generated by Django 3.2.21 on 2023-12-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_capsule_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picked_capsule',
            name='info_open_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='picked_capsule',
            name='info_write_date',
            field=models.DateTimeField(),
        ),
    ]
