# Generated by Django 4.2.5 on 2023-12-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20231227_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='picture',
            field=models.TextField(verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='picked_capsule',
            name='info_picture',
            field=models.TextField(),
        ),
    ]
